name: variant_conda_environment
channels:
  - conda-forge
  - bioconda
dependencies:
  # - bwa=0.7.* 
  - blast=2.10.*
  - fastqc=0.11.*
  - multiqc=1.6
  - bowtie2=2.4.*
  # - lofreq=2.1.*
  # - snpeff=5.0.*
  # - snpsift=4.3.*
  # - gatk4=4.0.* 
  - cutadapt=3.0
  - samtools=1.11
  # - bcftools=1.11
  # - vcftools=0.1.* 
  - seqtk=1.3
  - nextflow=20.10.*
  - r-base=4.0.*
  - r-tidyverse=1.3.*
  - r-openxlsx=4.2.* 
  # - r-egg=0.4.*
  # - r-pheatmap=1.0.*
  # - r-pdftools=2.3.*
  - cd-hit=4.8.*
  - cd-hit-auxtools=4.8.*
  # - spades=3.15.*
  # - perl-dbi=1.642
  # - perl-dbd-sqlite=1.64
  # - diamond=2.0.*
